client/src/app-components/people-list.js, client/src/data/fixtures/staff-fixtures.js, client/src/data/languages/cn.js, client/src/data/languages/de.js, client/src/data/languages/en.js, client/src/data/languages/es.js, client/src/data/languages/fr.js, client/src/data/languages/in.js, client/src/data/languages/it.js, client/src/data/languages/jp.js, client/src/data/languages/pt.js, client/src/data/languages/ru.js, client/src/data/languages/tr.js
Now, if a staff member was just created, the "Last login" shows "Never" instead of "undefined null at ...".
This also changes fixtures so that the change made can be shown.
=> Max Red - Solves issue #40 about last login

server/controllers/system/edit-settings.php, server/controllers/ticket/change-department.php, tests/system/edit-settings.rb
Reverts opensupports/opensupports#122
=> Revert "fix bug #58"

client/package.json, client/src/lib-app/fixtures-loader.js, client/src/lib-core/APIUtils.js
Early pull requests to allow easy review.
=> Replaces JQuery ajax requests with Axios requests

server/composer.json, server/controllers/article.php, server/controllers/staff.php, server/controllers/system.php, server/controllers/system/init-database.php, server/controllers/ticket.php, server/controllers/user.php, server/data/InitialMails.php, server/index.php, server/libs/Controller.php, server/libs/DataStoreList.php, server/libs/Validator.php, server/tests/controllers/user/loginTest.php, server/tests/libs/HashingTest.php, server/tests/libs/LinearCongruentialGeneratorTest.php, server/tests/libs/validations/captchaTest.php, server/tests/models/DataStoreTest.php, server/tests/models/MailTemplateTest.php, server/tests/models/ResponseTest.php
This replaces the manual file includes and closure based autoloaders with the built-in composer autoloader.
=> Use composer autoloader for source files (except tests)

client/src/app-components/ticket-viewer.js, client/src/app/admin/panel/articles/admin-panel-view-article.js, client/src/lib-app/mentions-parser.js
Early pull request for early review.
=> Mentions parser

server/data/MailTexts.php
There was a translation that was not dutch.
=> Fix dutch translation

client/src/app/admin/panel/articles/admin-panel-view-article.scss, client/src/app/main/dashboard/dashboard-article/dashboard-article-page.js, client/src/app/main/dashboard/dashboard-article/dashboard-article-page.scss, client/src/app/main/dashboard/dashboard-list-articles/dashboard-list-articles-page.js, client/src/app/main/dashboard/dashboard-list-articles/dashboard-list-articles-page.scss
This fixes the overflow problem we were having.
I suggest we augment this PR by limiting the longest size of titles on articles, what do you guys think? @ivandiazwm @guillegiu
=> UI articles

client/src/app-components/activity-row.js, server/controllers/ticket/comment.php, server/controllers/ticket/create.php, server/models/Log.php, server/models/Ticketevent.php, tests/system/disable-user-system.rb
* Users can comment on their tickets even if there is no user system.
* Notifications are correctly displayed even when the authors of those actions were deleted, showing a link to the profile only when possible.
* The session for a ticket is created as soon as the ticket is created.
* Tests
=> No user system comment bug - Fix notifications

client/src/app-components/ticket-event.js, client/src/app-components/ticket-event.scss, client/src/core-components/file-uploader.js, client/src/lib-app/__tests__/session-store-test.js, server/Makefile, server/libs/FileUploader.php, server/tests/controllers/user/loginTest.php
=> Add gif support, fix styling issues, fix login test

client/src/index.php
Reverts opensupports/opensupports#882
=> Revert "Adds Google platform.js script to index.php" for release

client/src/actions/session-actions.js, client/src/app/main/main-home/__tests__/main-home-page-login-widget-test.js, client/src/app/main/main-home/main-home-page-login-widget.js, client/src/index.html, server/Makefile, server/composer.json, server/controllers/user/login.php
Reverts opensupports/opensupports#881
=> Revert "Google social login" for release

client/src/app/admin/panel/admin-panel-menu.js, client/src/lib-app/search-tickets-utils.js
if I write "asd&tag=[1]" in the searchbox , it filters by “query=asd” and tag with” id = 1”
=> Fix error in searchbox in tickets/search-tickets

server/controllers/system/email-polling.php
This avoids data loss in case of an error. See also #895
=> Only erase all mails on success

client/src/app-components/ticket-viewer.js, client/src/app-components/ticket-viewer.scss
=> [DEV-132] Add reopen option after a ticket is closed

client/src/core-components/message.js, client/src/core-components/message.scss
=> [DEV-149] add close button to messages

server/composer.lock
Reverts opensupports/opensupports#1095
=> Revert "update composer lock"

client/src/app-components/ticket-viewer.js, client/src/app-components/ticket-viewer.scss
=> [DEV-128 ] - align response actions

client/src/app/admin/panel/tickets/admin-panel-my-tickets.scss, client/src/app/main/dashboard/dashboard-create-ticket/create-ticket-form.js, client/src/app/main/dashboard/dashboard-create-ticket/create-ticket-form.scss, client/src/core-components/modal.scss
=> [DEV-133] align close button

client/src/app/admin/panel/users/admin-panel-view-user.js, client/src/app/admin/panel/users/admin-panel-view-user.scss, client/src/data/languages/en.js
=> [DEV-213] add supervised user tooltip

client/src/app-components/ticket-viewer.scss
=> [DEV-128] add padding to ticket-viewer-info

client/src/app/admin/panel/dashboard/admin-panel-activity.scss
=> [DEV-228] Last activity menu style breaks in some languages

client/src/app-components/ticket-viewer.js, client/src/app-components/ticket-viewer.scss
=> [DEV-236] Modify edit ticket name padding and buttons 

client/src/app-components/language-selector.js, client/src/app/admin/panel/settings/admin-panel-email-settings.js
=> [DEV-215] Email template infinite loading 

client/src/index.php
Well I got a lot of errors in my logs just for this.
=> Fix undefined error

client/src/index.php
This reverts commit a5da776d2734f7aae1091d084f0eea978edb57ff.
=> Revert "Fix undefined error (#1129)"

README.md, client/package.json, client/src/actions/__mocks__/session-actions-mock.js, client/src/actions/__tests__/session-actions-test.js, client/src/actions/session-actions.js, client/src/app-components/session-expired-modal.js, client/src/data/languages/en.js, client/src/index.js, client/src/lib-app/api-call.js, client/src/lib-app/expired-session-utils.js, server/models/Session.php
- Increased lifetime of session cookie to **at least** 30 days
- When session expires when a user has the tab open, the next request will trigger a Modal to open:
- The modal will open first, then the user will be taken to the log in page
- Takes admin users to `/admin` and normal users to `/`
=> [DEV-143] Handle expired sessions
